import Product1 from '../assets/product-images/product1.jpg';
import Product2 from '../assets/product-images/product2.webp';
import Product3 from '../assets/product-images/product3.jpg';
import Product4 from '../assets/product-images/product4.webp';
// Add more product images as necessary

const products = [
  {
    id: 1,
    name: 'Derma cool',
    category: 'SkinCare',
    brand: 'NestCare',
    price: 238.85,
    originalPrice: 245.8,
    rating: 4.0,
    images: [Product1, Product2, Product1],
    discount: 'Save 35%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.',
      facts: ['High in protein', 'Low in fat', 'No artificial ingredients'],
      tableContent: {
        protein: '20g',
        fat: '5g',
        carbohydrates: '10g',
        sodium: '200mg',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.High in protein, Low in fat, No artificial ingredients',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Khandvi, breadcrumbs, Parmesan cheese, Italian seasoning',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.None known. Please consult with a physician if you have allergies.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Heat in a preheated oven at 375°F for 10-12 minutes.',
  },
  {
    id: 11,
    name: 'A medicine can take care of your skin',
    category: 'SkinCare',
    brand: 'NestCare',
    price: 238.85,
    originalPrice: 245.8,
    rating: 4.0,
    images: [Product1, Product2, Product1],
    discount: 'Save 35%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.',
      facts: ['High in protein', 'Low in fat', 'No artificial ingredients'],
      tableContent: {
        protein: '20g',
        fat: '5g',
        carbohydrates: '10g',
        sodium: '200mg',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.High in protein, Low in fat, No artificial ingredientsThese Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Khandvi, breadcrumbs, Parmesan cheese, Italian seasoningThese Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.None known. Please consult with a physician if you have allergies.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Heat in a preheated oven at 375°F for 10-12 minutes.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.',
  },
  {
    id: 2,
    name: 'Vitamin C Tablets',
    category: 'Vitamins&Minerals',
    brand: 'HealthCare Plus',
    price: 120.00,
    originalPrice: 150.00,
    rating: 4.5,
    images: [Product3, Product4],
    discount: 'Save 20%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Boost your immune system with these Vitamin C tablets. Great for daily use.',
      facts: ['Rich in Vitamin C', 'Boosts Immunity', 'No artificial colors'],
      tableContent: {
        vitaminC: '1000mg',
        servings: '30',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Boosts immunity, Antioxidant properties',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Vitamin C, cellulose, stearic acid',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.May cause upset stomach in some individuals.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Take one tablet daily with a meal.',
  },
  {
    id: 12,
    name: 'Mineral Tablets',
    category: 'Vitamins&Minerals',
    brand: 'HealthCare Plus',
    price: 120.00,
    originalPrice: 150.00,
    rating: 4.5,
    images: [Product3, Product4],
    discount: 'Save 20%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Boost your immune system with these Vitamin C tablets. Great for daily use.',
      facts: ['Rich in Vitamin C', 'Boosts Immunity', 'No artificial colors'],
      tableContent: {
        vitaminC: '1000mg',
        servings: '30',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Boosts immunity, Antioxidant properties',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Vitamin C, cellulose, stearic acid',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.May cause upset stomach in some individuals.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Take one tablet daily with a meal.',
  },
  {
    id: 3,
    name: 'Omega-3 Corn Oil',
    category: 'HeartHealth',
    brand: 'NutraBest',
    price: 299.99,
    originalPrice: 350.00,
    rating: 4.8,
    images: [Product1, Product2],
    discount: 'Save 15%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Support your heart health with these Omega-3 Fish Oil capsules, made from high-quality fish oil.',
      facts: ['Rich in Omega-3', 'Supports heart health', 'No fishy aftertaste'],
      tableContent: {
        omega3: '1200mg',
        epa: '360mg',
        dha: '240mg',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Supports heart health, Reduces inflammation',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Fish Oil, Gelatin, Glycerin, Water',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.May cause mild stomach discomfort.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Take two capsules daily with meals.',
  },
  {
    id: 13,
    name: 'OliveOil',
    category: 'HeartHealth',
    brand: 'NutraBest',
    price: 299.99,
    originalPrice: 350.00,
    rating: 4.8,
    images: [Product1, Product2],
    discount: 'Save 15%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Support your heart health with these Omega-3 Fish Oil capsules, made from high-quality fish oil.',
      facts: ['Rich in Omega-3', 'Supports heart health', 'No fishy aftertaste'],
      tableContent: {
        omega3: '1200mg',
        epa: '360mg',
        dha: '240mg',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Supports heart health, Reduces inflammation',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Fish Oil, Gelatin, Glycerin, Water',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.May cause mild stomach discomfort.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Take two capsules daily with meals.',
  },
  {
    id: 4,
    name: 'Herbal Hair Care Shampoo',
    category: 'PersonalCare',
    brand: 'Nature\'s Essence',
    price: 180.00,
    originalPrice: 200.00,
    rating: 4.3,
    images: [Product3, Product4],
    discount: 'Save 10%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.This herbal shampoo is made from natural ingredients to nourish your hair and scalp.',
      facts: ['Paraben-free', 'Sulfate-free', 'Enriched with herbs'],
      tableContent: {
        volume: '200ml',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Strengthens hair, Reduces hair fall',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Amla, Shikakai, Reetha, Aloe Vera',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.None known. Safe for all hair types.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Apply to wet hair, lather, and rinse thoroughly.',
  },
  {
    id: 14,
    name: 'Ayurvedic Hair Care Shampoo',
    category: 'PersonalCare',
    brand: 'Nature\'s Essence',
    price: 180.00,
    originalPrice: 200.00,
    rating: 4.3,
    images: [Product3, Product4],
    discount: 'Save 10%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.This herbal shampoo is made from natural ingredients to nourish your hair and scalp.',
      facts: ['Paraben-free', 'Sulfate-free', 'Enriched with herbs'],
      tableContent: {
        volume: '200ml',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Strengthens hair, Reduces hair fall',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Amla, Shikakai, Reetha, Aloe Vera',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.None known. Safe for all hair types.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Apply to wet hair, lather, and rinse thoroughly.',
  },
  {
    id: 5,
    name: 'Calcium Supplements',
    category: 'PersonalHealth',
    brand: 'StrongBones',
    price: 250.00,
    originalPrice: 300.00,
    rating: 4.7,
    images: [Product1, Product2],
    discount: 'Save 17%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Support your bone health with these calcium supplements. Ideal for daily use.',
      facts: ['High in calcium', 'Vitamin D3 enriched', 'Supports bone health'],
      tableContent: {
        calcium: '500mg',
        vitaminD3: '400 IU',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Supports bone density, Enhances calcium absorption',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Calcium Carbonate, Vitamin D3, Microcrystalline Cellulose',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.May cause constipation in some individuals.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Take one tablet twice daily with meals.',
  },
  {
    id: 15,
    name: 'Vitamins Supplements',
    category: 'PersonalHealth',
    brand: 'StrongBones',
    price: 250.00,
    originalPrice: 300.00,
    rating: 4.7,
    images: [Product1, Product2],
    discount: 'Save 17%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Support your bone health with these calcium supplements. Ideal for daily use.',
      facts: ['High in calcium', 'Vitamin D3 enriched', 'Supports bone health'],
      tableContent: {
        calcium: '500mg',
        vitaminD3: '400 IU',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Supports bone density, Enhances calcium absorption',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Calcium Carbonate, Vitamin D3, Microcrystalline Cellulose',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.May cause constipation in some individuals.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Take one tablet twice daily with meals.',
  },
  {
    id: 6,
    name: 'Herbal Skin Care Cream',
    category: 'SkinCare',
    brand: 'GlowNaturals',
    price: 220.00,
    originalPrice: 250.00,
    rating: 4.2,
    images: [Product3, Product4],
    discount: 'Save 12%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.This herbal cream is perfect for moisturizing and rejuvenating your skin.',
      facts: ['Paraben-free', 'Sulfate-free', 'Enriched with Aloe Vera'],
      tableContent: {
        volume: '100g',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Moisturizes skin, Improves skin texture',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Aloe Vera, Shea Butter, Vitamin E',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.None known. Safe for all skin types.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Apply to clean skin twice daily.',
  },
  {
    id: 16,
    name: 'Ayurvedic Skin Care Cream',
    category: 'SkinCare',
    brand: 'GlowNaturals',
    price: 220.00,
    originalPrice: 250.00,
    rating: 4.2,
    images: [Product3, Product4],
    discount: 'Save 12%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.This herbal cream is perfect for moisturizing and rejuvenating your skin.',
      facts: ['Paraben-free', 'Sulfate-free', 'Enriched with Aloe Vera'],
      tableContent: {
        volume: '100g',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Moisturizes skin, Improves skin texture',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Aloe Vera, Shea Butter, Vitamin E',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.None known. Safe for all skin types.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Apply to clean skin twice daily.',
  },
  {
    id: 7,
    name: 'Herbal Eye Drops',
    category: 'PersonalCare',
    brand: 'ClearVision',
    price: 150.00,
    originalPrice: 180.00,
    rating: 4.5,
    images: [Product1, Product2],
    discount: 'Save 17%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Relieve dry eyes and irritation with these herbal eye drops.',
      facts: ['Sterile', 'No preservatives', 'Soothing formula'],
      tableContent: {
        volume: '10ml',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Relieves dry eyes, Soothes irritation',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Rosewater, Aloe Vera, Glycerin',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.None known. Suitable for all ages.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Instill 1-2 drops in each eye as needed.',
  },
  {
    id: 17,
    name: 'Natural Eye Drops',
    category: 'PersonalCare',
    brand: 'ClearVision',
    price: 150.00,
    originalPrice: 180.00,
    rating: 4.5,
    images: [Product1, Product2],
    discount: 'Save 17%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Relieve dry eyes and irritation with these herbal eye drops.',
      facts: ['Sterile', 'No preservatives', 'Soothing formula'],
      tableContent: {
        volume: '10ml',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Relieves dry eyes, Soothes irritation',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Rosewater, Aloe Vera, Glycerin',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.None known. Suitable for all ages.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Instill 1-2 drops in each eye as needed.',
  },
  {
    id: 8,
    name: 'Organic Multivitamin Gummies',
    category: 'Vitamins&Minerals',
    brand: 'HealthyBites',
    price: 320.00,
    originalPrice: 400.00,
    rating: 4.6,
    images: [Product3, Product4],
    discount: 'Save 20%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These organic gummies provide a balanced blend of essential vitamins and minerals.',
      facts: ['Gluten-free', 'Non-GMO', 'Delicious flavor'],
      tableContent: {
        servings: '30',
        calories: '15',
        sugar: '2g',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Supports overall health, Boosts energy levels',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Vitamin C, Vitamin D3, Zinc, Biotin',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.May cause mild digestive upset.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Take two gummies daily with meals.',
  },
  {
    id: 18,
    name: 'Gummies Vitamin Oraganic',
    category: 'Vitamins&Minerals',
    brand: 'HealthyBites',
    price: 320.00,
    originalPrice: 400.00,
    rating: 4.6,
    images: [Product3, Product4],
    discount: 'Save 20%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These organic gummies provide a balanced blend of essential vitamins and minerals.',
      facts: ['Gluten-free', 'Non-GMO', 'Delicious flavor'],
      tableContent: {
        servings: '30',
        calories: '15',
        sugar: '2g',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Supports overall health, Boosts energy levels',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Vitamin C, Vitamin D3, Zinc, Biotin',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.May cause mild digestive upset.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Take two gummies daily with meals.',
  },
  {
    id: 19,
    name: 'Relief Pain Balm',
    category: 'HeartHealth',
    brand: 'ReliefNow',
    price: 85.00,
    originalPrice: 100.00,
    rating: 4.1,
    images: [Product1, Product2],
    discount: 'Save 15%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.This fast-acting pain relief balm is perfect for soothing muscle and joint aches.',
      facts: ['Non-greasy', 'Quick absorption', 'Long-lasting effect'],
      tableContent: {
        volume: '50g',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Provides fast pain relief, Reduces inflammation',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Menthol, Camphor, Eucalyptus Oil',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.For external use only. Avoid contact with eyes.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Apply a small amount to the affected area and massage gently.',
  },
  {
    id: 10,
    name: 'Herbal Sleep Aid Capsules',
    category: 'HeartHealth',
    brand: 'CalmRest',
    price: 180.00,
    originalPrice: 220.00,
    rating: 4.4,
    images: [Product3, Product4],
    discount: 'Save 18%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These herbal capsules are formulated to promote restful sleep and relaxation.',
      facts: ['Non-habit forming', 'All-natural ingredients', 'Supports restful sleep'],
      tableContent: {
        servings: '30',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Promotes restful sleep, Reduces anxiety',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Valerian Root, Chamomile, Melatonin',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.May cause drowsiness. Use with caution when driving or operating machinery.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Take one capsule 30 minutes before bedtime.',
  },
  {
    id: 20,
    name: 'Heartohealth Sleep Aid Capsules',
    category: 'HeartHealth',
    brand: 'CalmRest',
    price: 180.00,
    originalPrice: 220.00,
    rating: 4.4,
    images: [Product3, Product4],
    discount: 'Save 18%',
    description: {
      longDescription: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These herbal capsules are formulated to promote restful sleep and relaxation.',
      facts: ['Non-habit forming', 'All-natural ingredients', 'Supports restful sleep'],
      tableContent: {
        servings: '30',
      },
    },
    keyBenefits: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Promotes restful sleep, Reduces anxiety',
    ingredients: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Valerian Root, Chamomile, Melatonin',
    sideEffects: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.May cause drowsiness. Use with caution when driving or operating machinery.',
    howToUse: 'These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.These Italian-style Khandvi Dokla are made from all-natural ingredients. Perfect for any meal, they are easy to prepare and delicious.Take one capsule 30 minutes before bedtime.',
  },
  // Add similar structure for 10 more products
];

export default products;
